version: '3.8'

services:
  app:
    container_name: container-app
    image: ivanjuniordocker/conversao-peso:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80